# aca importamos randon para generar un mensaje aleatorio , de tomar alcohol ,solo y aconpañado.
import random


def tomar_solo(nombre: str) -> str:
    MENSAJE_CON_ALCOHOL = [
        f"!Que lindo {nombre} tomando solo, termino todo el barril de cerveza !",
        f"{nombre} toma solo todo el tequila y se siente bien.",
        f"Que lindo dijo tomar agua {nombre} y se tomo todo el whisky.",
        f"Lo mejor de la vida es ver a {nombre} hacer desaparecer el ron que habia.",
        f"{nombre} tomo todo el vermut, no quedo ni una gota  .",
        f"!Eres mago {nombre}, desaparecio el mojito que estaba en la mesa!",
        f"Estando solo {nombre} probo el gin y no paro hasta ver el fin .",
        f"Brindando solo {nombre} no dejo ni la etiqueta de la botella de grapa-miel.",
        f"El licor de huevo no es para tomar solo {nombre}, pero lo hizo igual.",
        f"El vino tinto no es para tomar solo {nombre}, pero lo hizo igual.",
        f"El vino blanco no es para tomar solo {nombre}, pero lo hizo igual.",
        f"El vino rosado no es para tomar solo {nombre}, pero lo hizo igual.",
        f"La sidra no es para tomar solo {nombre}, pero lo hizo igual.",
        f"el licor de pera vio su fin en el vaso de {nombre}.",
        f"La cerveza negra no es para tomar solo {nombre}, pero lo hizo igual.",
        f"Que ensalada de frutas que se mando {nombre} con el licor de frutas.",
        f"El licor de arroz es un trago fuerte para tomar solo {nombre}, pero igual no dejaste que eso te detuviera.",
        f"El licor de chocolate se derritio en el vaso de {nombre}.",
        f"El licor de caramelo endulzo la vida de {nombre}.",
        f"Mas que en casco de roble , fue en el estomago de {nombre} que termino el whisky.",
        f"Un gran vikingo {nombre} tomando hidromiel solo.",
        f"El licor de manzana se fue con {nombre}.",
        f"El licor de banana se fue con {nombre} ahora se cree mono !!!.",
        f"Queria se astronauta {nombre} y se tomo todo el licor de coco.",
        f"El licor de menta se fue con {nombre} lindo aliento, pero no camina derecho.",
        f"{nombre} tomo todo el licor de durazno y se puso colorado.",
        f"{nombre} tomo todo el licor de frutilla y se puso dulce.",
        f"El licor de huevo penso que era pascua {nombre} y se lo tomo todo.",
        f"El licor de nuez se fue con {nombre} y se puso duro.",
        f"El licor de almendra se fue con {nombre} y se puso dulce.",
        f"El licor de anana se fue con {nombre} y se puso tropical.",
        f"El licor de cafe se fue con {nombre} y ahora no se puede dormir!!!.",
        f"Gran buscador de tesoros {nombre} encontro el licor de oro.",
        f"El oude jenever se fue con {nombre} y se puso viejo.",
        f"Alguien vio al licor de rosas? {nombre} se lo tomo todo.",
        f"El licor de tequila se fue con {nombre} y ahora no se puede levantar!!!.",
        f"Dice que el licor de uva es bueno para el corazon {nombre} se lo tomo todo.",
        f"{nombre} y el licor de coco se fueron a la playa, pero solo regreso {nombre}.",
        f"Queria sacarse la sed {nombre} y se tomo todo el licor de sandia.",
        f"Tenia frio {nombre} y se tomo todo el licor de canela.",
        f"El curacao azul se fue con {nombre} y ahora no puede parar de hablar.",
        f"Buscas el calvados? {nombre} se lo tomo todo.",
        f"{nombre} se cree Serbio y se tomo todo el rakija.",
        f"{nombre} se cree ruso y se tomo todo el vodka.",
        f"Se fue a pescar {nombre} y se tomo todo el aquavit.",
    ]
    return random.choice(MENSAJE_CON_ALCOHOL)


def tomar_acompañado(invitador: str, invitado: str) -> str:
    INVITAR_ALCOHOL = [
        f"Increible {invitador} invita a {invitado} a tomar cerveza.",
        f"{invitador} invita a {invitado} a tomar tequila.",
        f"Que lindo ver a {invitador} invitar a {invitado} a tomar whisky.",
        f"Lo mejor de la vida es ver a {invitador} invitar a {invitado} a tomar ron.",
        f"{invitador} invita a {invitado} a tomar vermut.",
        f"!Que lindo ver a {invitador} invitar a {invitado} a tomar gin.",
        f"Invitacion de {invitador} a {invitado} para tomar mojito.",
        f"De un salto {invitador} invita a {invitado} a tomar grapa-miel.",
        f"Sorpresa {invitado}, {invitador} te invita a tomar licor de huevo.",
        f"{invitador} invita a {invitado} a tomar vino tinto.",
        f"{invitador} invita a {invitado} a tomar vino blanco.",
        f"{invitador} invita a {invitado} a tomar vino rosado.",
        f"{invitador} invita a {invitado} a tomar sidra.",
        f"{invitador} invita a {invitado} a tomar licor de pera.",
        f"{invitador} invita a {invitado} a tomar cerveza negra.",
        f"{invitador} invita a {invitado} a tomar licor de frutas.",
        f"{invitador} invita a {invitado} a tomar licor de arroz,de un sake.",
        f"{invitador} invita a {invitado} a tomar licor de chocolate.",
        f"{invitador} invita a {invitado} a tomar licor de caramelo.",
        f"{invitador} invita a {invitado} a que pruebe un pisco sour que le preparo.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de durazno.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de frutilla.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de huevo.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de nuez.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de almendra.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de anana.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de cafe.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de oro.",
        f"{invitador} invita a {invitado} a tomar un shot de oude jenever.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de rosas.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de tequila.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de uva.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de coco.",
        f"El licor de coco se fue con {invitador} y {invitado}.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de sandia.",
        f"{invitador} invita a {invitado} a tomar un shot de licor de canela.",
        f"{invitador} invita a {invitado} a tomar un shot de curacao azul.",
        f"{invitador} invita a {invitado} a tomar un shot de calvados.",
        f"{invitador} invita a {invitado} a tomar un shot de rakija.",
        f"{invitador} invita a {invitado} a tomar un shot de vodka.",
        f"{invitador} invita a {invitado} a tomar un shot de aquavit.",
        f"Yo {invitador} invito a {invitado} a disfrutar un negroni clasico.",
        f"Te sugiero yo {invitador} que pruebes un buen fernet con coca{invitado}.",
        f"{invitador} Dice, que te parece si probamos un buen gin tonic {invitado}?",
        f"{invitador} Le ofrece a {invitado} un buen daiquiri de frutilla.",
        f"{invitador} Le ofrece a {invitado} un coctel misterioso!!! .",
    ]
    return random.choice(INVITAR_ALCOHOL)
